"""Synthesised sound effects: the §14 layer, with no assets to license.

The doctrine asks for whooshes, risers and impact hits; the honest blocker
was always assets -- this machine ships none, and inventing a requirement
for downloaded packs contradicts §15's own rule. The way out is synthesis:
every sound here is generated by FFmpeg from first principles (filtered
noise sweeps, sine risers, low sine bursts with fast decay), which makes
them royalty-free by construction and identical on every machine.

Generated once into the data root's asset store and reused; regeneration is
cheap and deterministic, so the files are cattle, not pets. The mix layer
decides *where* they play -- this module only makes them exist and describes
them.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Final

from backend.core.logging import LogChannel, get_logger

logger = get_logger("rendering.sfx", LogChannel.RENDERING)

#: Bumped when a recipe changes, so old files stop matching and regenerate.
SFX_VERSION: Final[int] = 1


@dataclass(frozen=True, slots=True)
class SfxRecipe:
    """One synthesised sound: its name, length, and the FFmpeg that makes it."""

    name: str
    seconds: float
    #: The lavfi source + filter chain producing the sound, sans I/O.
    source: str
    filters: str


#: The library. Each recipe is written for its §14 role:
#: * ``impact`` — a low sine burst with fast decay: the bass hit under a
#:   heavy moment.
#: * ``hit`` — shorter, brighter; the punctuation for a punch-in.
#: * ``whoosh`` — band-passed noise swept by volume: the transition breath.
#: * ``riser`` — a climbing sine under swelling noise: tension into payoff.
RECIPES: Final[tuple[SfxRecipe, ...]] = (
    SfxRecipe(
        name="impact",
        seconds=0.9,
        source="aevalsrc=sin(2*PI*55*t)*exp(-6*t):d=0.9:s=48000",
        filters="alimiter=limit=0.9,afade=t=out:st=0.6:d=0.3",
    ),
    SfxRecipe(
        name="hit",
        seconds=0.4,
        source="aevalsrc=sin(2*PI*110*t)*exp(-14*t)+0.3*sin(2*PI*220*t)*exp(-20*t):d=0.4:s=48000",
        filters="alimiter=limit=0.9",
    ),
    SfxRecipe(
        name="whoosh",
        seconds=1.1,
        source="anoisesrc=colour=pink:duration=1.1:sample_rate=48000",
        filters=(
            "bandpass=frequency=900:width_type=o:width=1.5,"
            "volume='if(lt(t,0.55),t/0.55,(1.1-t)/0.55)':eval=frame,"
            "alimiter=limit=0.8"
        ),
    ),
    SfxRecipe(
        name="riser",
        seconds=2.0,
        source="aevalsrc=0.5*sin(2*PI*(80+160*t)*t)*(t/2):d=2:s=48000",
        filters="highpass=f=60,alimiter=limit=0.8,afade=t=out:st=1.8:d=0.2",
    ),
)


def sfx_dir(data_root: Path) -> Path:
    """Where the synthesised set lives (§84: inside the data root)."""
    return data_root / "assets" / "sfx" / f"v{SFX_VERSION}"


def generation_arguments(recipe: SfxRecipe, destination: Path) -> list[str]:
    """The argv that synthesises one recipe, runner-executed like all argv."""
    return [
        "-f",
        "lavfi",
        "-i",
        recipe.source,
        "-af",
        recipe.filters,
        "-ar",
        "48000",
        "-ac",
        "2",
        str(destination),
    ]


def ensure_sfx(data_root: Path, ffmpeg: Any) -> dict[str, Path]:
    """The full set, generated on first use, returned by name.

    Never raises: a machine whose FFmpeg cannot synthesise a recipe simply
    fields a smaller set, and the mix places nothing it does not have.
    """
    directory = sfx_dir(data_root)
    produced: dict[str, Path] = {}
    for recipe in RECIPES:
        destination = directory / f"{recipe.name}.wav"
        if destination.is_file():
            produced[recipe.name] = destination
            continue
        try:
            directory.mkdir(parents=True, exist_ok=True)
            ffmpeg.run(
                [*ffmpeg.base_arguments(), *generation_arguments(recipe, destination)],
                timeout_seconds=60,
            )
        except Exception:
            logger.exception("Could not synthesise a sound", extra={"name": recipe.name})
            continue
        if destination.is_file():
            produced[recipe.name] = destination
    if produced:
        logger.info("Synthesised sound set ready", extra={"sounds": sorted(produced)})
    return produced


__all__ = ["RECIPES", "SFX_VERSION", "SfxRecipe", "ensure_sfx", "generation_arguments", "sfx_dir"]
