-- Initial schema: the core entities of SPEC section 45, plus the job system
-- of sections 46/81 and the analysis cache of section 48.
--
-- Conventions
--   * Identifiers are TEXT, generated by backend/core/ids.py.
--   * Timestamps are TEXT in ISO-8601 UTC ("2026-08-10T12:00:00.000000+00:00").
--     SQLite has no datetime type and text sorts chronologically.
--   * Times inside media are REAL seconds from the start of the source.
--   * Structured extras are TEXT holding JSON, always with a DEFAULT so a row
--     never carries SQL NULL where the model expects an object.
--   * Every child table cascades from its parent, so deleting a project
--     removes its analysis without orphan rows.
--
-- The duration CHECK below restates the 600/3600 second product limits from
-- backend/core/duration.py because SQL cannot import Python. A unit test
-- (tests/unit/test_duration.py) fails if the two ever disagree.

CREATE TABLE projects (
    id                      TEXT PRIMARY KEY,
    name                    TEXT NOT NULL,
    created_at              TEXT NOT NULL,
    updated_at              TEXT NOT NULL,
    status                  TEXT NOT NULL DEFAULT 'created',

    target_duration_seconds INTEGER NOT NULL,
    mode                    TEXT NOT NULL DEFAULT 'story',
    game                    TEXT NOT NULL DEFAULT 'auto',
    detected_game           TEXT,
    resolution              INTEGER NOT NULL DEFAULT 1080,
    fps                     INTEGER NOT NULL DEFAULT 60,
    aspect_ratio            TEXT NOT NULL DEFAULT '16:9',
    language                TEXT NOT NULL DEFAULT 'auto',

    project_directory       TEXT NOT NULL,
    version                 INTEGER NOT NULL DEFAULT 1,

    application_version     TEXT NOT NULL,
    analysis_version        INTEGER NOT NULL,
    schema_version          INTEGER NOT NULL,

    CHECK (target_duration_seconds >= 600 AND target_duration_seconds <= 3600),
    CHECK (version >= 1),
    CHECK (length(name) > 0)
);

CREATE INDEX idx_projects_status ON projects (status);
CREATE INDEX idx_projects_updated_at ON projects (updated_at DESC);

-- Source recordings. Referenced, never rewritten (§42).
CREATE TABLE media (
    id                  TEXT PRIMARY KEY,
    project_id          TEXT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    role                TEXT NOT NULL DEFAULT 'gameplay',
    state               TEXT NOT NULL DEFAULT 'registered',

    source_path         TEXT NOT NULL,
    filename            TEXT NOT NULL,
    container           TEXT NOT NULL,
    size_bytes          INTEGER NOT NULL,
    checksum            TEXT NOT NULL,
    checksum_algorithm  TEXT NOT NULL DEFAULT 'sha256',

    -- Populated by the PROBE stage (Phase 2); NULL until then.
    duration_seconds    REAL,
    width               INTEGER,
    height              INTEGER,
    fps                 REAL,
    video_codec         TEXT,
    audio_codec         TEXT,
    sample_rate         INTEGER,
    channels            INTEGER,
    bitrate             INTEGER,
    has_video           INTEGER,
    has_audio           INTEGER,

    created_at          TEXT NOT NULL,
    updated_at          TEXT NOT NULL,
    error_code          TEXT,
    error_message       TEXT,

    CHECK (size_bytes >= 0),
    CHECK (duration_seconds IS NULL OR duration_seconds >= 0),

    -- The same file cannot be imported into one project twice (§48 identity).
    UNIQUE (project_id, checksum)
);

CREATE INDEX idx_media_project ON media (project_id);
CREATE INDEX idx_media_role ON media (project_id, role);

CREATE TABLE media_tracks (
    id           TEXT PRIMARY KEY,
    media_id     TEXT NOT NULL REFERENCES media (id) ON DELETE CASCADE,
    track_index  INTEGER NOT NULL,
    kind         TEXT NOT NULL,
    codec        TEXT,
    language     TEXT,
    width        INTEGER,
    height       INTEGER,
    fps          REAL,
    sample_rate  INTEGER,
    channels     INTEGER,
    bitrate      INTEGER,
    is_default   INTEGER NOT NULL DEFAULT 0,

    UNIQUE (media_id, track_index)
);

CREATE INDEX idx_media_tracks_media ON media_tracks (media_id);

-- Pipeline stage executions (§46, §81). One row per stage attempt group;
-- retries update the row and increment attempt.
CREATE TABLE analysis_jobs (
    id               TEXT PRIMARY KEY,
    project_id       TEXT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    media_id         TEXT REFERENCES media (id) ON DELETE CASCADE,
    stage            TEXT NOT NULL,
    status           TEXT NOT NULL DEFAULT 'queued',

    progress         REAL NOT NULL DEFAULT 0.0,
    message          TEXT,

    attempt          INTEGER NOT NULL DEFAULT 0,
    max_attempts     INTEGER NOT NULL DEFAULT 3,

    error_code       TEXT,
    error_message    TEXT,
    cancel_requested INTEGER NOT NULL DEFAULT 0,

    created_at       TEXT NOT NULL,
    started_at       TEXT,
    completed_at     TEXT,
    duration_seconds REAL,

    payload          TEXT NOT NULL DEFAULT '{}',
    result           TEXT NOT NULL DEFAULT '{}',

    CHECK (progress >= 0.0 AND progress <= 1.0),
    CHECK (attempt >= 0),
    CHECK (max_attempts >= 1),

    -- One job per (project, media, stage): resume updates it rather than
    -- queueing a duplicate (§47).
    UNIQUE (project_id, media_id, stage)
);

CREATE INDEX idx_jobs_project ON analysis_jobs (project_id);
CREATE INDEX idx_jobs_status ON analysis_jobs (status);
CREATE INDEX idx_jobs_stage ON analysis_jobs (project_id, stage);

-- Analysis cache index (§48). The key encodes video hash + model version +
-- analysis version; the payload is a path to the artefact on disk.
CREATE TABLE analysis_cache (
    cache_key        TEXT PRIMARY KEY,
    project_id       TEXT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    media_id         TEXT REFERENCES media (id) ON DELETE CASCADE,
    namespace        TEXT NOT NULL,
    artefact_path    TEXT NOT NULL,
    size_bytes       INTEGER NOT NULL DEFAULT 0,

    model_name       TEXT,
    model_version    TEXT,
    prompt_id        TEXT,
    prompt_version   INTEGER,
    analysis_version INTEGER NOT NULL,

    created_at       TEXT NOT NULL,
    last_used_at     TEXT NOT NULL,

    CHECK (size_bytes >= 0)
);

CREATE INDEX idx_cache_project ON analysis_cache (project_id);
CREATE INDEX idx_cache_namespace ON analysis_cache (project_id, namespace);

-- Physical shot boundaries (§17). Supporting information, not edit points.
CREATE TABLE scenes (
    id            TEXT PRIMARY KEY,
    project_id    TEXT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    media_id      TEXT NOT NULL REFERENCES media (id) ON DELETE CASCADE,
    scene_index   INTEGER NOT NULL,
    start_seconds REAL NOT NULL,
    end_seconds   REAL NOT NULL,
    change_score  REAL,
    keyframe_path TEXT,

    CHECK (start_seconds >= 0),
    CHECK (end_seconds > start_seconds),
    UNIQUE (media_id, scene_index)
);

CREATE INDEX idx_scenes_media_time ON scenes (media_id, start_seconds);

-- Sampled frames (§16). Hierarchical: base, high-activity, candidate.
CREATE TABLE frames (
    id              TEXT PRIMARY KEY,
    project_id      TEXT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    media_id        TEXT NOT NULL REFERENCES media (id) ON DELETE CASCADE,
    timestamp       REAL NOT NULL,
    sampling_level  TEXT NOT NULL DEFAULT 'base',
    image_path      TEXT NOT NULL,
    width           INTEGER,
    height          INTEGER,
    motion_score    REAL,
    analyzed        INTEGER NOT NULL DEFAULT 0,

    CHECK (timestamp >= 0),
    UNIQUE (media_id, timestamp, sampling_level)
);

CREATE INDEX idx_frames_media_time ON frames (media_id, timestamp);
CREATE INDEX idx_frames_unanalyzed ON frames (media_id, analyzed);

-- Audio events (§18): spikes, silence, shouting, explosions.
CREATE TABLE audio_events (
    id            TEXT PRIMARY KEY,
    project_id    TEXT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    media_id      TEXT NOT NULL REFERENCES media (id) ON DELETE CASCADE,
    track_role    TEXT NOT NULL DEFAULT 'gameplay',
    event_type    TEXT NOT NULL,
    start_seconds REAL NOT NULL,
    end_seconds   REAL NOT NULL,
    confidence    REAL NOT NULL DEFAULT 1.0,
    rms_db        REAL,
    peak_db       REAL,
    lufs          REAL,
    metadata      TEXT NOT NULL DEFAULT '{}',

    CHECK (start_seconds >= 0),
    CHECK (end_seconds >= start_seconds),
    CHECK (confidence >= 0.0 AND confidence <= 1.0)
);

CREATE INDEX idx_audio_events_media_time ON audio_events (media_id, start_seconds);
CREATE INDEX idx_audio_events_type ON audio_events (project_id, event_type);

-- Speech (§14). Word timestamps live in the JSON `words` column so a segment
-- and its words are always written together.
CREATE TABLE transcript_segments (
    id            TEXT PRIMARY KEY,
    project_id    TEXT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    media_id      TEXT NOT NULL REFERENCES media (id) ON DELETE CASCADE,
    segment_index INTEGER NOT NULL,
    start_seconds REAL NOT NULL,
    end_seconds   REAL NOT NULL,
    text          TEXT NOT NULL,
    language      TEXT,
    speaker       TEXT,
    confidence    REAL,
    words         TEXT NOT NULL DEFAULT '[]',

    CHECK (start_seconds >= 0),
    CHECK (end_seconds >= start_seconds),
    UNIQUE (media_id, segment_index)
);

CREATE INDEX idx_transcript_media_time ON transcript_segments (media_id, start_seconds);

-- Gameplay events (§21, §26). `sources` records which detectors agreed (§27).
CREATE TABLE game_events (
    id            TEXT PRIMARY KEY,
    project_id    TEXT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    media_id      TEXT NOT NULL REFERENCES media (id) ON DELETE CASCADE,
    event_type    TEXT NOT NULL,
    start_seconds REAL NOT NULL,
    end_seconds   REAL NOT NULL,
    confidence    REAL NOT NULL,
    importance    REAL NOT NULL DEFAULT 0.0,
    sources       TEXT NOT NULL DEFAULT '[]',
    game_profile  TEXT,
    metadata      TEXT NOT NULL DEFAULT '{}',

    -- Model provenance for every AI-generated result (§49).
    model_name       TEXT,
    model_version    TEXT,
    prompt_version   INTEGER,
    analysis_version INTEGER NOT NULL,

    created_at    TEXT NOT NULL,

    CHECK (start_seconds >= 0),
    CHECK (end_seconds >= start_seconds),
    CHECK (confidence >= 0.0 AND confidence <= 1.0),
    CHECK (importance >= 0.0 AND importance <= 1.0)
);

CREATE INDEX idx_game_events_media_time ON game_events (media_id, start_seconds);
CREATE INDEX idx_game_events_type ON game_events (project_id, event_type);

-- Moments (§28-§34): one or more correlated events plus expanded context.
CREATE TABLE moments (
    id                  TEXT PRIMARY KEY,
    project_id          TEXT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    media_id            TEXT NOT NULL REFERENCES media (id) ON DELETE CASCADE,
    moment_type         TEXT NOT NULL,

    -- Core event span, and the span after context expansion (§29).
    start_seconds       REAL NOT NULL,
    end_seconds         REAL NOT NULL,
    context_start       REAL NOT NULL,
    context_end         REAL NOT NULL,

    score               REAL NOT NULL DEFAULT 0.0,
    confidence          REAL NOT NULL DEFAULT 0.0,
    dead_time_score     REAL NOT NULL DEFAULT 0.0,
    repetition_score    REAL NOT NULL DEFAULT 0.0,

    -- Per-dimension breakdown (§32) and the human-readable justification (§80).
    score_breakdown     TEXT NOT NULL DEFAULT '{}',
    explanation         TEXT NOT NULL DEFAULT '[]',
    event_ids           TEXT NOT NULL DEFAULT '[]',

    needs_review        INTEGER NOT NULL DEFAULT 0,
    -- User overrides from the review screen (§78, §121).
    user_state          TEXT NOT NULL DEFAULT 'auto',

    thumbnail_path      TEXT,
    analysis_version    INTEGER NOT NULL,
    created_at          TEXT NOT NULL,

    CHECK (start_seconds >= 0),
    CHECK (end_seconds >= start_seconds),
    CHECK (context_start >= 0),
    CHECK (context_end >= context_start),
    CHECK (context_start <= start_seconds),
    CHECK (context_end >= end_seconds),
    CHECK (confidence >= 0.0 AND confidence <= 1.0)
);

CREATE INDEX idx_moments_project_score ON moments (project_id, score DESC);
CREATE INDEX idx_moments_media_time ON moments (media_id, start_seconds);
CREATE INDEX idx_moments_type ON moments (project_id, moment_type);

-- Timeline (§40, §41). Non-destructive: clips reference source timestamps.
CREATE TABLE timeline_clips (
    id              TEXT PRIMARY KEY,
    project_id      TEXT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    media_id        TEXT NOT NULL REFERENCES media (id) ON DELETE CASCADE,
    moment_id       TEXT REFERENCES moments (id) ON DELETE SET NULL,

    track           TEXT NOT NULL DEFAULT 'video',
    clip_index      INTEGER NOT NULL,

    source_in       REAL NOT NULL,
    source_out      REAL NOT NULL,
    timeline_start  REAL NOT NULL,
    timeline_end    REAL NOT NULL,

    speed           REAL NOT NULL DEFAULT 1.0,
    transition_in   TEXT NOT NULL DEFAULT 'cut',
    transition_out  TEXT NOT NULL DEFAULT 'cut',
    enabled         INTEGER NOT NULL DEFAULT 1,
    metadata        TEXT NOT NULL DEFAULT '{}',

    CHECK (source_in >= 0),
    CHECK (source_out > source_in),
    CHECK (timeline_start >= 0),
    CHECK (timeline_end > timeline_start),
    CHECK (speed > 0),
    UNIQUE (project_id, track, clip_index)
);

CREATE INDEX idx_clips_project_time ON timeline_clips (project_id, timeline_start);

-- Declarative effects (§68). Times are relative to the clip when clip_id is
-- set, otherwise to the timeline.
CREATE TABLE timeline_effects (
    id              TEXT PRIMARY KEY,
    project_id      TEXT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    clip_id         TEXT REFERENCES timeline_clips (id) ON DELETE CASCADE,
    effect_type     TEXT NOT NULL,
    start_seconds   REAL NOT NULL,
    duration_seconds REAL NOT NULL,
    parameters      TEXT NOT NULL DEFAULT '{}',
    enabled         INTEGER NOT NULL DEFAULT 1,

    CHECK (start_seconds >= 0),
    CHECK (duration_seconds > 0)
);

CREATE INDEX idx_effects_project ON timeline_effects (project_id);
CREATE INDEX idx_effects_clip ON timeline_effects (clip_id);

-- Captions (§71). Timing always derives from transcript timestamps.
CREATE TABLE captions (
    id              TEXT PRIMARY KEY,
    project_id      TEXT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    clip_id         TEXT REFERENCES timeline_clips (id) ON DELETE CASCADE,
    caption_index   INTEGER NOT NULL,
    timeline_start  REAL NOT NULL,
    timeline_end    REAL NOT NULL,
    text            TEXT NOT NULL,
    language        TEXT,
    words           TEXT NOT NULL DEFAULT '[]',
    style           TEXT NOT NULL DEFAULT '{}',

    CHECK (timeline_start >= 0),
    CHECK (timeline_end > timeline_start),
    UNIQUE (project_id, caption_index)
);

CREATE INDEX idx_captions_project_time ON captions (project_id, timeline_start);

-- Local, user-provided music only (§73).
CREATE TABLE music (
    id              TEXT PRIMARY KEY,
    project_id      TEXT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    file_path       TEXT NOT NULL,
    title           TEXT,
    timeline_start  REAL NOT NULL DEFAULT 0.0,
    timeline_end    REAL,
    gain_db         REAL NOT NULL DEFAULT -18.0,
    ducking_enabled INTEGER NOT NULL DEFAULT 1,
    loop_enabled    INTEGER NOT NULL DEFAULT 1,

    CHECK (timeline_start >= 0),
    CHECK (timeline_end IS NULL OR timeline_end > timeline_start)
);

CREATE INDEX idx_music_project ON music (project_id);

CREATE TABLE renders (
    id                TEXT PRIMARY KEY,
    project_id        TEXT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    status            TEXT NOT NULL DEFAULT 'queued',
    engine            TEXT NOT NULL DEFAULT 'ffmpeg',
    output_path       TEXT,

    resolution        INTEGER NOT NULL,
    fps               INTEGER NOT NULL,
    video_codec       TEXT,
    audio_codec       TEXT,
    encoder           TEXT,

    duration_seconds  REAL,
    size_bytes        INTEGER,

    started_at        TEXT,
    completed_at      TEXT,
    render_seconds    REAL,
    error_code        TEXT,
    error_message     TEXT,

    project_version   INTEGER NOT NULL DEFAULT 1,
    created_at        TEXT NOT NULL,

    CHECK (duration_seconds IS NULL OR duration_seconds >= 0),
    CHECK (size_bytes IS NULL OR size_bytes >= 0)
);

CREATE INDEX idx_renders_project ON renders (project_id, created_at DESC);

-- QA results (§76, §77). One row per check so warnings are never collapsed.
CREATE TABLE qa_results (
    id            TEXT PRIMARY KEY,
    project_id    TEXT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    render_id     TEXT REFERENCES renders (id) ON DELETE CASCADE,
    category      TEXT NOT NULL DEFAULT 'technical',
    check_name    TEXT NOT NULL,
    status        TEXT NOT NULL,
    detail        TEXT,
    measured      TEXT NOT NULL DEFAULT '{}',
    created_at    TEXT NOT NULL
);

CREATE INDEX idx_qa_render ON qa_results (render_id);
CREATE INDEX idx_qa_project_status ON qa_results (project_id, status);

-- Delivery layer.
--
-- Not part of §45's core entities: these tables exist so that adding a
-- destination later (YouTube auto-publish, or any other) is additive. The MVP
-- writes only local_file rows here. Storing the metadata now means the
-- narrative stage can fill in title, description and chapters as it goes,
-- instead of that work being retrofitted when a destination appears.

CREATE TABLE video_metadata (
    project_id     TEXT PRIMARY KEY REFERENCES projects (id) ON DELETE CASCADE,
    title          TEXT NOT NULL DEFAULT '',
    description    TEXT NOT NULL DEFAULT '',
    tags           TEXT NOT NULL DEFAULT '[]',
    category       TEXT,
    language       TEXT NOT NULL DEFAULT 'auto',
    visibility     TEXT NOT NULL DEFAULT 'private',
    thumbnail_path TEXT,
    chapters       TEXT NOT NULL DEFAULT '[]',
    made_for_kids  INTEGER NOT NULL DEFAULT 0,
    updated_at     TEXT NOT NULL,

    CHECK (length(title) <= 100),
    CHECK (length(description) <= 5000)
);

CREATE TABLE publications (
    id                TEXT PRIMARY KEY,
    project_id        TEXT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    render_id         TEXT NOT NULL REFERENCES renders (id) ON DELETE CASCADE,
    target            TEXT NOT NULL,
    status            TEXT NOT NULL DEFAULT 'pending',

    external_id       TEXT,
    external_url      TEXT,
    output_path       TEXT,

    error_code        TEXT,
    error_message     TEXT,

    -- What was actually sent, so later edits to the project do not rewrite the
    -- record of a past publication.
    metadata_snapshot TEXT NOT NULL DEFAULT '{}',

    requested_at      TEXT NOT NULL,
    completed_at      TEXT
);

CREATE INDEX idx_publications_project ON publications (project_id, requested_at DESC);
CREATE INDEX idx_publications_render ON publications (render_id);

-- Interaction layer.
--
-- Sits above the pipeline: editing instructions, questions and commands. The
-- pipeline reads only the resolved intent and never these tables directly, so
-- the whole layer can be ignored by a user who never opens the chat.

-- The resolved intent, cached. Rebuildable at any time from the update log
-- below, which is the authority.
CREATE TABLE editing_intents (
    project_id  TEXT PRIMARY KEY REFERENCES projects (id) ON DELETE CASCADE,
    preset      TEXT NOT NULL,
    resolved    TEXT NOT NULL DEFAULT '{}',
    updated_at  TEXT NOT NULL
);

-- Ordered log of intent changes. Instructions accumulate rather than replace,
-- so a follow-up ("and fewer effects") keeps everything said before it.
CREATE TABLE editing_intent_updates (
    id          TEXT PRIMARY KEY,
    project_id  TEXT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    sequence    INTEGER NOT NULL,
    source      TEXT NOT NULL,
    raw_text    TEXT,
    delta       TEXT NOT NULL DEFAULT '{}',
    confidence  REAL NOT NULL DEFAULT 1.0,
    created_at  TEXT NOT NULL,

    CHECK (sequence >= 0),
    CHECK (confidence >= 0.0 AND confidence <= 1.0),
    UNIQUE (project_id, sequence)
);

CREATE INDEX idx_intent_updates_project ON editing_intent_updates (project_id, sequence);

-- Conversation history, per project.
CREATE TABLE conversation_messages (
    id               TEXT PRIMARY KEY,
    project_id       TEXT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    role             TEXT NOT NULL,
    interaction_type TEXT,
    text             TEXT NOT NULL,
    payload          TEXT NOT NULL DEFAULT '{}',
    created_at       TEXT NOT NULL
);

CREATE INDEX idx_conversation_project ON conversation_messages (project_id, created_at);

-- Edit versions: a snapshot of intent plus timeline, so "go back to the
-- previous version" restores an edit without re-analysing anything.
CREATE TABLE edit_versions (
    id          TEXT PRIMARY KEY,
    project_id  TEXT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    version     INTEGER NOT NULL,
    label       TEXT,
    reason      TEXT,
    intent      TEXT NOT NULL DEFAULT '{}',
    clips       TEXT NOT NULL DEFAULT '[]',
    created_at  TEXT NOT NULL,

    CHECK (version >= 1),
    UNIQUE (project_id, version)
);

CREATE INDEX idx_edit_versions_project ON edit_versions (project_id, version DESC);
