"""Domain models shared by every layer.

These Pydantic models are the contract between the pipeline stages, the
database, the local API and the UI. Nothing here knows about FFmpeg, Remotion,
Whisper or SQLite -- §123 keeps the five layers separable.
"""

from backend.core.models.enums import (
    AudioEventType,
    DeadTimeCategory,
    DetectorSource,
    EffectType,
    GameEventType,
    HardwareProfile,
    HealthStatus,
    JobStage,
    JobStatus,
    MediaRole,
    MediaState,
    MomentType,
    ProjectStatus,
    QAStatus,
    ReactionType,
    RenderEngine,
    TrackKind,
    TransitionType,
    VideoMode,
)
from backend.core.models.health import HealthCheck, HealthReport
from backend.core.models.jobs import (
    ANALYSIS_STAGES,
    EDIT_STAGES,
    STAGE_DEPENDENCIES,
    Job,
    ProjectStageStatus,
    dependencies_of,
    dependents_of,
    downstream_of,
    runnable_stages,
    stages_in_order,
    validate_stage_graph,
)
from backend.core.models.media import (
    SUPPORTED_AUDIO_CONTAINERS,
    SUPPORTED_CONTAINERS,
    Media,
    MediaImport,
    MediaMetadata,
    MediaTrack,
)
from backend.core.models.project import (
    Project,
    ProjectCreate,
    ProjectManifest,
    ProjectUpdate,
    utcnow,
)

__all__ = [
    "ANALYSIS_STAGES",
    "EDIT_STAGES",
    "STAGE_DEPENDENCIES",
    "SUPPORTED_AUDIO_CONTAINERS",
    "SUPPORTED_CONTAINERS",
    "AudioEventType",
    "DeadTimeCategory",
    "DetectorSource",
    "EffectType",
    "GameEventType",
    "HardwareProfile",
    "HealthCheck",
    "HealthReport",
    "HealthStatus",
    "Job",
    "JobStage",
    "JobStatus",
    "Media",
    "MediaImport",
    "MediaMetadata",
    "MediaRole",
    "MediaState",
    "MediaTrack",
    "MomentType",
    "Project",
    "ProjectCreate",
    "ProjectManifest",
    "ProjectStageStatus",
    "ProjectStatus",
    "ProjectUpdate",
    "QAStatus",
    "ReactionType",
    "RenderEngine",
    "TrackKind",
    "TransitionType",
    "VideoMode",
    "dependencies_of",
    "dependents_of",
    "downstream_of",
    "runnable_stages",
    "stages_in_order",
    "utcnow",
    "validate_stage_graph",
]
